### ISSUE TITLE
Add GitHub Actions

### ISSUE THREAD

**Issue by arnaubennassar** [0xPolygon/agglayer#2]
- [x] build and push docker images (introduced through #65)
- [x] lint (introduced through #16)
- [x] test (introduced through #19)

**Comment by Stefan-Ethernal** [comment]
All issues have been resolved, so mark this issue as done.
